### ISSUE TITLE
id attribute added to <br> are not always removed from source

### ISSUE THREAD

**Issue by picov** [covistefan/summernote-br#3]
While using the plugin with real content (basic HTML text formatted with only p,b,i,u tags) I've noticed that the id attribute of br is not being always removed correctly from source.

A simple case of this behavior occurs when you split multiple times two identical parts:
Example
1) Starting content source:
`<p>mama<p>`

2) shift+enter into the middle of the string correctly produces this source:
`<p>ma<br class="note-lb">ma</p>`

3) but another shift+enter incorrectly produces this source:
`<p><br class="note-lb">ma<br class="note-lb"><br class="note-lb" id="24251">ma</p>`

4) and then another shift+enter incorrectly produces this source
`mam<br class="note-lb">a`

(when this happens sometimes the summernote editing area render incorrectly and stop working even if you set content from the source view)

**Comment by covistefan** [comment]
i think using the context.invoke in the new version should have solved your described bug and made it all a bit smaller, faster and bug free ..

**Comment by picov** [comment]
Yes, works much better now!
Is there another way to move editing point to the new line (after shift+click) without inserting also a  `&VeryThinSpace;` ?

**Comment by covistefan** [comment]
Sorry. I could not figure out another way yet. Will have a look from time to time while working on another plugin, maybe i‘ll find a better solution on the fly ..

Have an idea. Will try to solve it when arriving in office later this evening.
