### ISSUE TITLE
how to default to <br>?

### ISSUE THREAD

**Issue by maotou316** [covistefan/summernote-br#4]
This code is really great!

but how to set default to <BR>
and Shift+Enter to <P> 

thanks

**Comment by demon101** [comment]
following settings can be used  
`$.summernote.dom.emptyPara = "<div><br/></div>";`

**Comment by covistefan** [comment]
i think the request meant how to default get a soft break when hitting enter ... i'm working on it ...

**Comment by demon101** [comment]
Dear @covistefan , do you have any estimations? When it will be ready? The improvement will be very useful for me too

**Comment by covistefan** [comment]
it's solved with the new release

**Comment by demon101** [comment]
@covistefan  was that intended?
`context.invoke('editor.pasteHTML', '<br />&VeryThinSpace;');`
